FROM node:12-alpine as base

EXPOSE 7890

RUN apk add --no-cache tini

WORKDIR /app

COPY package*.json ./

RUN npm install && npm cache clean --force

COPY . .

ENTRYPOINT ["/sbin/tini", "--"]

CMD ["node", "server.ts]